### ISSUE TITLE
can you update some tutorials?show how to use it pls

### ISSUE THREAD

**Issue by HuanDeng** [fahadsiddiqui3/Touch-Keypad-STM32F7DISCO-using-Emwin#2]

**Comment by fahadsiddiqui3** [comment]
How to use :

1)Include keypad.h in the parent window file. Add Virtual_Keyboard.c file in the project. 
2)Create a Parent window of the screen resolution of the LCD display.
3)Pass the handle of the parent window to the API CreateKeypad() and you're done. Call this only after the parent window is created.
4)The handle of the keyboard is _hKeyboard and can be used as showing or hiding the keypad. Use WM_ShowWindow(_hKeyboard) to display the keyboard.
5)The keyboard can be configured as numeric as well as alphanumeric by API Config_Keyboard(). Pass the maximum length of data, and edit box ID wherever the pressed key character needs to be displayed.

**Comment by fahadsiddiqui3** [comment]
Would be happy if you test and update the page :) Anyway this keypad works nicely and you don't need to bother about the size of window.

**Comment by HuanDeng** [comment]
Thank you very much, I have discovered how to use it myself before, but I am very happy to receive your reply
